version: '3.7'

services:
  charge-controller:
    environment:
      - DEV=${DEV}
    image: solar-protocol/charge-controller
    restart: always
    volumes:
      - data:/data
  api:
    image: solar-protocol/api
    restart: always
    volumes:
      - data:/data
    ports:
      - 11215:80
  web:
    image: nginx
    restart: always
    volumes:
      - data:/data
      - frontend:/frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11221:80
  solar-protocol:
    image: solar-protocol/protocol
    restart: always
    command: python runner.py now
    volumes:
      - data:/data
      - frontend:/frontend
      - local:/local

volumes:
  data:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/../data'
  frontend:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/../frontend'
  local:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/../local'
