name: build solar pi image

on: ['pull_request', 'workflow_dispatch']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: get_version
        uses: battila7/get-version-action@v2

      # create 'solar-pi-stage' stage 
      - run: |
          mkdir -p solar-pi-stage/00-install-container-runtime &&
          echo docker.io > solar-pi-stage/00-install-container-runtime/00-packages &&
          echo usermod --append --groups docker solar > solar-pi-stage/00-install-container-runtime/01-run-chroot.sh &&
          chmod +x solar-pi-stage/00-install-container-runtime/01-run-chroot.sh &&
          mkdir -p solar-pi-stage/01-build-container-images &&
          echo git > solar-pi-stage/01-build-container-images/00-packages &&
          {
          cat > solar-pi-stage/01-build-container-images/01-run-chroot.sh <<-EOF
          #!/bin/bash -e
          su - solar --command "git clone https://github.com/alexnathanson/solar-protocol.git --branch beta /home/solar/solar-protocol"
          su - solar --command "/home/solar/solar-protocol/solar-protocol install"
          su - solar --command "/home/solar/solar-protocol/solar-protocol build"
          EOF
          } && chmod +x solar-pi-stage/01-build-container-images/01-run-chroot.sh &&
          {
          cat > solar-pi-stage/prerun.sh <<-EOF
          #!/bin/bash -e
          if [ ! -d "\${ROOTFS_DIR}" ]; then copy_previous; fi
          EOF
          } && chmod +x solar-pi-stage/prerun.sh

      - name: build image
        uses: usimd/pi-gen-action@v1
        id: build
        with:
          ## USER SETTINGS
          enable-ssh: 1
          hostname: solar-pi
          username: solar
          password: 'solarpowerforartists'

          keyboard-keymap: us
          keyboard-layout: English (US)
          locale: en_US.UTF-8
          timezone: America/New_York

          wpa-country: 'US'

          ## BUILD + OUTPUT SETTINGS
          compression: xz
          enable-noobs: false
          github-token: ${{ github.token }}
          image-name: 'solar-pi'
          pi-gen-version: arm64
          use-qcow2: 1

          release: bullseye
          stage-list: stage0 stage1 stage2 ./solar-pi-stage


      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Solar Pi ${{ steps.get_version.outputs.version-without-v }}
          files: ${{ steps.build.outputs.image-path }}
          draft: true

